Models/MovieContext.cs
using Microsoft.EntityFrameworkCore;

namespace MovieKnights.Models
{
    public class MovieContext : DbContext
    {
        public MovieContext(DbContextOptions<MovieContext> options) : base(options)
        {}

        public DbSet<User> User { get; set; }
        public DbSet<Watch> Watch { get; set; }
    }
}

Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MovieKnights.Models
{
    public class User
    {
       public int id { get; set; } 

       [Required]
       [MaxLength(100)]
       public string Email { get; set; }

       [Required]
       [MinLength(8)]
       [MaxLength(512)]
       public string Password { get; set; }

       [Required]
       [MaxLength(1)]
       public string Status { get; set; }

    public ICollection<Watch> Watchs { get; set; }

    }   

    
}

Models/Watch.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MovieKnights.Models
{
    public class Watch
    {
        public int id { get; set; } 
        [Required]
        public DateTime DateAdded { get; set; } 
        [Required]
        [MaxLength(1)]
        public string Status { get; set; } 

        public int UserID { get; set; } 
        public User User { get; set; } 
        [Required]
        public string MovieID { get; set; } 
    }
}

Pages/Cast.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;

namespace MovieKnights.Pages
{
    public class CastModel : PageModel
    {
        public string castID ="";
        public void OnGet()
        {
            castID = Program.History.GetCastID();
            
        }
    }//class
}//namespace

Pages/CreateUser.cshtml.cs
using System;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;

namespace MovieKnights.Pages
{
    public class CreateUserModel : PageModel
    
    {
        public int UserID = Program.History.GetUserID();
        public void OnGet()
        {}

        public void OnPostCreateUser(string email, string password)
        {
            using(SqlConnection myConn = new SqlConnection(Program.Fetch.cs))
            {
                SqlCommand createUser = new SqlCommand();
                createUser.Connection = myConn;
                myConn.Open();

                createUser.Parameters.AddWithValue("@email", email);
                createUser.Parameters.AddWithValue("@password", password);

                createUser.CommandText = ("[spCreateUser]");
                createUser.CommandType = System.Data.CommandType.StoredProcedure;

                createUser.ExecuteNonQuery();
            }
        }
    }//class
}//namespace

Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MovieKnights.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data.SqlClient;

namespace MovieKnights.Pages
{
    public class IndexModel : PageModel
    {
        public List<string> id = new List<string>();
        public List<string> posterPath = new List<string>();
        public List<string> VidClips = new List<string>();
        public List<string> Filter = new List<string>();

        public List<string> CastIDs = new List<string>();
        public List<string> CastNames = new List<string>();
        public List<string> CastImages = new List<string>();

        public string description = "";
        public string movieTitle = "";
        
        public int UserID = Program.History.GetUserID();
        //get methods
        public async Task OnGet()//automaticall load prev search done
        {
            string prevSearch = Program.History.GetSearch();
            if(prevSearch != "")
            {
                await OnPostFindMovies(prevSearch);
            }
            UserID = Program.History.GetUserID();
        }
///post  method

//OnPostlogin

        public void OnPostLogin(string email, string password)
        {
            using(SqlConnection myConn = new SqlConnection(Program.Fetch.cs))
            {
                SqlCommand login = new SqlCommand();
                login.Connection = myConn;
                myConn.Open();

                login.Parameters.AddWithValue("@email", email);
                login.Parameters.AddWithValue("@password", password);

                login.CommandText = ("[spLoginReturnID]");
                login.CommandType = System.Data.CommandType.StoredProcedure;

               var result = login.ExecuteScalar(); // need return value
               if(result != null)
               {
                    Program.History.SetUserID(Convert.ToInt32(result)); 
               }
               Response.Redirect("/Index");
            }//using
        }//on post login

        //on post logout
        public void OnPostLogout()
        {
            Program.History.Logout();
             Response.Redirect("/Index");
        }

        public void OnPostCast(string castID)
        {

            Program.History.SetCastID(castID);
            Response.Redirect("/cast");
        }

        public async Task OnPostDetails(string movieID)
        {
            await Program.Fetch.GrabMovieDetails(movieID);

            //==========>>
            // Videos
            Program.JsonNinja = new JsonNinja(Program.Fetch.Videos);
            Filter = Program.JsonNinja.GetDetails("\"results\"");
            Program.JsonNinja = new JsonNinja(Filter[0]);

            List<string> vidNames = Program.JsonNinja.GetNames();
            List<string> vidVals = Program.JsonNinja.GetVals();

            VidClips = Program.JsonNinja.GetDetails("\"key\"");

            //===========>>
            // Details
            Program.JsonNinja = new JsonNinja(Program.Fetch.Details);

            List<string> detailNames = Program.JsonNinja.GetNames();
            List<string> detailVals = Program.JsonNinja.GetVals();

            List<string> descs = Program.JsonNinja.GetDetails("\"overview\"");
            description = descs[0];
        
            //===========>>
            // Cast

            Program.JsonNinja = new JsonNinja(Program.Fetch.Credits);
            List<string> creditNames = Program.JsonNinja.GetNames();
            List<string> creditVals = Program.JsonNinja.GetVals();

            Filter = Program.JsonNinja.GetDetails("\"cast\"");
            Program.JsonNinja = new JsonNinja(Filter[0]);
            CastIDs = Program.JsonNinja.GetIds("\"id\"");
            CastNames = Program.JsonNinja.GetDetails("\"name\"");
            CastImages = Program.JsonNinja.GetDetails("\"profile_path\"");

           
        }
        public async Task OnPostFindMovies(string search)
        {
            Program.History.SetSearch(search);
            await Program.Fetch.GrabMovieInfo(search);

            if(Program.Fetch.Data == null)
            {
                // oops no data to display
            }
            else
            {
                Program.JsonNinja = new JsonNinja(Program.Fetch.Data);
                Program.JsonNinja = new JsonNinja(Program.JsonNinja.filter[0]);
                posterPath = Program.JsonNinja.GetPosters();

                // hack to fix the last poster path with missing 'g'
                // there has to a better way ;)
                posterPath[posterPath.Count() - 1] += "g";

                id = Program.JsonNinja.GetIds("\"id\"");

            }
        } // OnPostFindMovies()
    } // class
} // namespace

Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MovieKnights.Pages
{
    public class PrivacyModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Pages/Cast.cshtml
@page
@model CastModel


<div id="castHeader">
    <img id="castHeaderProfilePic" src="http://placehold.it/200x200" alt="Cast Pic">
    <p id="castHeaderProfileName"> Scarlett johansson </p>
</div>    
<div id="basicInfo" >
    <table id="infoTable">
        <tr>
            <td>Name:</td>
            <td>scarlett johansson</td>
        </tr>
         <tr>
            <td>Age:</td>
            <td>37</td>
        </tr>
         <tr>
            <td>Country:</td>
            <td>USA</td>
        </tr>
    </table>
</div>
<div id="photoGallery">
    @for(int i=0; i < 30; i++)
    {
        <img src="https://placehold.it/120x180" alt="gallery pic" + @i>
    }
</div>

Pages/CreateUser.cshtml
@page
@model CreateUserModel

<div id="createUser">
    <form id="createUserForm" method="post" asp-page-handler="CreateUser">
        <input type="email" name="email" placeholder="enter  email"><br>
        <input type="password" name="password" placeholder="enter  password"><br>
        <input type="submit" value="create account">
    </form>
</div>

Pages/Index.cshtml
@page
@model IndexModel

<!-- Search Results -->
<div id="searchResults">
    <form id="searchImage" method="post" asp-page-handler="Details">
        @for(int i = 0; i < Model.posterPath.Count; i++)
        {
            if(Model.posterPath[i] != "")
            {
                if(Model.posterPath[i].Length > 4)
                {
                    string style = "background: url(https://image.tmdb.org/t/p/w500/" + @Model.posterPath[i] + ");";
                    style += " background-size: cover; background-position: center;";
                    style += " width: 18%; display: inline-block; margin: 1%;";
                    style += " border-radius: 16px; border: 2px solid #444;";
                    <div name="movieID" value="@Model.id[i]" style="@style">
                        <input class="thumbBtn" type="submit" name="movieID" value="@Model.id[i]">
                    </div>
                }
            }
        }
    </form>
</div>

<!-- Movie Details -->
<div id="movieDetails">
    @if(Model.description.Length > 300)
    {
        <p class="movieDesc">@Model.description.Substring(0, 297)...</p>
    }
    else
    {
        <p class="movieDesc">@Model.description</p>
    }
</div>

<!-- Video Output -->
<div id="video">
    <div class="frameDiv">
        @for(int i = 0; i < Model.VidClips.Count; i++)
        {
            @if(i < 4)
            {
                <iframe src="https://www.youtube.com/embed/@Model.VidClips[i]"
                    class="frame" frameborder="3" 
                    allow="autoplay; encrypted-media"
                    allowfullscreen>
                </iframe>
            }
        }
    </div>
</div>

<!-- cast info -->
<div id="cast">
    <form method="post" asp-page-handler="Cast">
        @for(int i=0;i < Model.CastImages.Count; i++)
        {
            @if(i < 12)
            {
                @if(Model.CastImages[i].Length > 4)
                {
                    string cID = Model.CastIDs[i];
                    string style ="background: url(https://image.tmdb.org/t/p/w500/" + @Model.CastImages[i] + ");";

                    style += "background-size: cover; background-position: center;";
                    style += "width: 175px; height: 175px; display: inline-block;";
                    <div name="castID" value="@cID" class="castPic"
                    style="@style">
                    <input type="submit" name="castID" class="castBtn" value="@cID"
                        style="min-width: 175px; min-height: 175px;" />
                    </div>
                }
            }
        }
    </form>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>MovieKnights</title>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link href="https://fonts.googleapis.com/css?family=Baloo&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <!-- login page -->

    <div id="loginPanel">
        @if(Model.UserID == null || Model.UserID == 0)
        {
            <form id="loginForm" method="post" asp-page-handler="Login">
                <input type="email" name="email" placeholder="enter your email"><br>
                <input type="password" name="password" placeholder="enter your password"><br>
                <input type="submit" value="login">             
            </form>
        }
        else
         {
            <form id="logoutForm" method="post" asp-page-handler="Logout">
                <input type="submit" value="logout">             
            </form>
        }
        <h3 onclick="ToggleLogin();">login/logout</h3>
    </div>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">MovieKnights</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Admin">Admin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div id="logo">
        <img class="mkLogo" src="~/assets/images/logo.png" alt="Movie Knights">
    </div>
    <div id="search">
        <form class="form form-group" id="search_form" method="post" asp-page-handler="FindMovies">
            <input class="form form-control" name="search" type="text" placeholder="type movie name">
            <input class="btn btn-success" name="search" type="submit" value="Search">
        </form>
    </div>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - MovieKnights - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>